### ISSUE TITLE
geth compatibility

### ISSUE THREAD

**Issue by achempion** [poanetwork/poa-explorer#184] opened 2018-05-16 08:02 UTC
Hi, first, thank you for the awesome project and that you've decided to open source it.

Right now, the app looks like compatible with `parity` and `geth` RPC-api except one thing:
https://github.com/poanetwork/poa-explorer/blob/master/apps/explorer/lib/explorer/chain/transaction.ex#L10

The `geth` rpc-api doesn't have such fields as `public_key` and `standard_v`.

Maybe we ought to remove it. Also, we can extract `public_key` from current data that we're getting from `geth` and I think that `standard_v` as well.

**Comment by acravenho** [comment] 2018-05-16 08:14
@achempion Thank you for this info. Our team will talk this over today and will follow up with any questions or comments.

**Comment by acravenho** [comment] 2018-05-16 12:50
Duplicate of #183

**Closed** 2018-05-16 12:51 UTC
Labels: enhancement
